ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS source VARCHAR(10) NOT NULL DEFAULT 'express';

CREATE INDEX IF NOT EXISTS idx_rl_source ON request_logs (source);

CREATE TABLE IF NOT EXISTS ingest_state (
  name VARCHAR(40) PRIMARY KEY,
  inode BIGINT,
  byte_offset BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
